language: python

cache: pip

sudo: required

services:
  - docker

before_install:
  - pip install tox
  - docker build -t project-411 .
  - docker run -d -p 80:5000 project-411

script:
  - tox
  - curl -ILX GET 0.0.0.0:80
